---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_facts.os_family == 'Debian'

    - name: Install git (required for dotfiles clone).
      ansible.builtin.package:
        name: git
        state: present

  roles:
    - role: bernylinville.dotfiles
